### ISSUE TITLE
Incompatibility with Supplementaries

### ISSUE THREAD

**Issue by NyakoFox** [CodexAdrian/ConnectedTexturesMod-Fabric#1]
Information in this issue: https://github.com/MehVahdJukaar/Supplementaries/issues/395

**Comment by ground-fruit** [comment]
By disabling CTM in it's configs, the missing-texture box is removed. However, some Supplementaries things are invisible - see screenshot below:
![2023-02-25_07 55 25](https://user-images.githubusercontent.com/105956363/221360787-1d2870bf-9acc-40b7-b28a-3c3851bbac2a.png)

the lantern and sign should have a post from the wall.
The flower pot should have string hanging from the ceiling.
