### ISSUE TITLE
Missing Texture Glitch/Bug with Chipped and Supplementaries 

### ISSUE THREAD

**Issue by RealxRancor** [CodexAdrian/ConnectedTexturesMod-Fabric#7]
![2023-03-02_16 39 12](https://user-images.githubusercontent.com/101079144/222476543-9f91f3d3-113e-4e63-8e8d-b3cb0ea1635c.png)

i already was on the discord from supplementaries and they found out its a issue with ctm..sadly

The Admin/Dev from there said this at last: ctm isnt loading up the parents of those models. i can only see that far
[16:30]
should i mark the mods as incompatible?
[16:35]
https://github.com/CodexAdrian/ConnectedTexturesMod-Fabric/blob/1.19/src/main/java/team/chisel/ctm/client/handler/ModelsAddedCallbackHandler.java#L41 this is whats failing. idk much about ctm inner working to say more. Its giving that method instead of ModelBakery::getModel to the getMaterials method resulting in it getting a missing model as parent

and said i should ask here whats wrong and if u can fix it

**Comment by DEAFG0AT** [comment]
Same issue here! I've discovered more missing textures. Here is my [original report](https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues/635) on the Supplementaries bug page.

Mixing textures I've discovered so far:
- Flower Box
- Wall Lantern
- Any block you put into the timer frame
- Hanging sign (all variants)

**Comment by M0nkeyPr0grammer** [comment]
I have also ran into the same issues

**Comment by SteveNichols5** [comment]
Same issue, been around for a long time. Would be nice to have a fix.
